language: cpp

branches:
  only:
    - master

sudo: required
dist: trusty

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq -y install cxxtest

script:
  -  make CXXFLAGS="-O0 -Wall -Wextra --coverage" LDFLAGS="--coverage" -C tests test

after_success:
  - ./.travis/after_success.sh

