name: Build and Test
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - CXX: g++
          - CXX: clang++
    name: "Build (${{ matrix.compiler.CXX }})"
    runs-on: ubuntu-latest
    env:
      CFLAGS: -O2 -Wall -Werror
      CXX: ${{ matrix.compiler.CXX }}
    steps:
      - name: Check out the source code
        uses: actions/checkout@v5

      - name: Install dependencies
        run: sudo apt-get -qq update && sudo apt-get -qq install libgtest-dev

      - name: Build
        run: cmake -B build -DCMAKE_CXX_COMPILER="${{ matrix.compiler.CXX }}" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Wall -Werror" && cmake --build build

      - name: Test
        run: ctest
        working-directory: build
